-- Generated from pret/poketcg src/data/cards.asm and attack_animations.asm.
-- Card labels and ordered command sequences remain source-identical.
local Animations = {}

Animations.card_attacks = {
  ["AbraCard"] = { "ATK_ANIM_PSYCHIC_HIT", "ATK_ANIM_NONE" },
  ["AerodactylCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_HIT" },
  ["AlakazamCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_CONFUSE_RAY" },
  ["ArbokCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_POISON_FANG" },
  ["ArcanineLv34Card"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_FIRE_SPIN" },
  ["ArcanineLv45Card"] = { "ATK_ANIM_BIG_FLAME", "ATK_ANIM_HIT_RECOIL" },
  ["ArticunoLv35Card"] = { "ATK_ANIM_BEAM", "ATK_ANIM_BLIZZARD" },
  ["ArticunoLv37Card"] = { "ATK_ANIM_QUICKFREEZE", "ATK_ANIM_WHIRLWIND_ZIGZAG" },
  ["BeedrillCard"] = { "ATK_ANIM_NEEDLES", "ATK_ANIM_NEEDLES" },
  ["BellsproutCard"] = { "ATK_ANIM_WHIP", "ATK_ANIM_GLOW_EFFECT" },
  ["BlastoiseCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_HYDRO_PUMP" },
  ["BulbasaurCard"] = { "ATK_ANIM_DRAIN", "ATK_ANIM_NONE" },
  ["ButterfreeCard"] = { "ATK_ANIM_WHIRLWIND", "ATK_ANIM_DRAIN" },
  ["CaterpieCard"] = { "ATK_ANIM_STRING_SHOT", "ATK_ANIM_NONE" },
  ["ChanseyCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_HIT_RECOIL" },
  ["CharizardCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_FIRE_SPIN" },
  ["CharmanderCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_SMALL_FLAME" },
  ["CharmeleonCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_BIG_FLAME" },
  ["ClefableCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_PROTECT" },
  ["ClefairyCard"] = { "ATK_ANIM_SING", "ATK_ANIM_NONE" },
  ["CloysterCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_NEEDLES" },
  ["CuboneCard"] = { "ATK_ANIM_CRY", "ATK_ANIM_HIT" },
  ["DewgongCard"] = { "ATK_ANIM_BEAM", "ATK_ANIM_BEAM" },
  ["DiglettCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_HIT" },
  ["DittoCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_GLOW_EFFECT" },
  ["DodrioCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_BIG_HIT" },
  ["DoduoCard"] = { "ATK_ANIM_MULTIPLE_SLASH", "ATK_ANIM_NONE" },
  ["DragonairCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_HYPER_BEAM" },
  ["DragoniteLv41Card"] = { "ATK_ANIM_HEALING_WIND", "ATK_ANIM_HIT" },
  ["DragoniteLv45Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_HIT" },
  ["DratiniCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["DrowzeeCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_CONFUSE_RAY" },
  ["DugtrioCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_HIT" },
  ["EeveeCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_QUICK_ATTACK" },
  ["EkansCard"] = { "ATK_ANIM_SPIT_POISON", "ATK_ANIM_HIT" },
  ["ElectabuzzLv20Card"] = { "ATK_ANIM_BARRIER", "ATK_ANIM_QUICK_ATTACK" },
  ["ElectabuzzLv35Card"] = { "ATK_ANIM_THUNDERSHOCK", "ATK_ANIM_THUNDERPUNCH" },
  ["ElectrodeLv35Card"] = { "ATK_ANIM_SONICBOOM", "ATK_ANIM_GLOW_EFFECT" },
  ["ElectrodeLv42Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_CHAIN_LIGHTNING" },
  ["ExeggcuteCard"] = { "ATK_ANIM_HYPNOSIS", "ATK_ANIM_DRAIN" },
  ["ExeggutorCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_BIG_HIT" },
  ["FarfetchdCard"] = { "ATK_ANIM_WHIP", "ATK_ANIM_POT_SMASH" },
  ["FearowCard"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_DRILL" },
  ["FlareonLv22Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_HIT" },
  ["FlareonLv28Card"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_BIG_FLAME" },
  ["FlyingPikachuCard"] = { "ATK_ANIM_THUNDERSHOCK", "ATK_ANIM_QUICK_ATTACK" },
  ["GastlyLv17Card"] = { "ATK_ANIM_GOO", "ATK_ANIM_ENERGY_CONVERSION" },
  ["GastlyLv8Card"] = { "ATK_ANIM_SLEEPING_GAS", "ATK_ANIM_GLOW_EFFECT" },
  ["GengarCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_DARK_MIND" },
  ["GeodudeCard"] = { "ATK_ANIM_STONE_BARRAGE", "ATK_ANIM_NONE" },
  ["GloomCard"] = { "ATK_ANIM_POISON_POWDER", "ATK_ANIM_FOUL_ODOR" },
  ["GolbatCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_DRAIN" },
  ["GoldeenCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["GolduckCard"] = { "ATK_ANIM_PSYCHIC_HIT", "ATK_ANIM_HYPER_BEAM" },
  ["GolemCard"] = { "ATK_ANIM_ROCK_THROW", "ATK_ANIM_BIG_SELFDESTRUCTION" },
  ["GravelerCard"] = { "ATK_ANIM_PROTECT", "ATK_ANIM_ROCK_THROW" },
  ["GrimerCard"] = { "ATK_ANIM_GOO", "ATK_ANIM_PROTECT" },
  ["GrowlitheCard"] = { "ATK_ANIM_SMALL_FLAME", "ATK_ANIM_NONE" },
  ["GyaradosCard"] = { "ATK_ANIM_DRAGON_RAGE", "ATK_ANIM_BUBBLES" },
  ["HaunterLv17Card"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_NIGHTMARE" },
  ["HaunterLv22Card"] = { "ATK_ANIM_HYPNOSIS", "ATK_ANIM_PSYCHIC_HIT" },
  ["HitmonchanCard"] = { "ATK_ANIM_PUNCH", "ATK_ANIM_PUNCH" },
  ["HitmonleeCard"] = { "ATK_ANIM_STRETCH_KICK", "ATK_ANIM_PUNCH" },
  ["HorseaCard"] = { "ATK_ANIM_DARK_GAS", "ATK_ANIM_NONE" },
  ["HypnoCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_DARK_MIND" },
  ["IvysaurCard"] = { "ATK_ANIM_WHIP", "ATK_ANIM_POWDER_HIT_POISON" },
  ["JigglypuffLv12Card"] = { "ATK_ANIM_RECOVER", "ATK_ANIM_HIT_RECOIL" },
  ["JigglypuffLv13Card"] = { "ATK_ANIM_NONE", "ATK_ANIM_EXPAND" },
  ["JigglypuffLv14Card"] = { "ATK_ANIM_LULLABY", "ATK_ANIM_HIT" },
  ["JolteonLv24Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_NEEDLES" },
  ["JolteonLv29Card"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_NEEDLES" },
  ["JynxCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_PSYCHIC_HIT" },
  ["KabutoCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_SLASH" },
  ["KabutopsCard"] = { "ATK_ANIM_SONICBOOM", "ATK_ANIM_DRAIN" },
  ["KadabraCard"] = { "ATK_ANIM_RECOVER", "ATK_ANIM_PSYCHIC_HIT" },
  ["KakunaCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_POWDER_EFFECT_CHANCE" },
  ["KangaskhanCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_PUNCH" },
  ["KinglerCard"] = { "ATK_ANIM_BIG_HIT", "ATK_ANIM_HIT" },
  ["KoffingCard"] = { "ATK_ANIM_FOUL_GAS", "ATK_ANIM_NONE" },
  ["KrabbyCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_HIT" },
  ["LaprasCard"] = { "ATK_ANIM_WATER_GUN", "ATK_ANIM_CONFUSE_RAY" },
  ["LickitungCard"] = { "ATK_ANIM_GOO", "ATK_ANIM_SUPERSONIC" },
  ["MachampCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_SEISMIC_TOSS" },
  ["MachokeCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_HIT_RECOIL" },
  ["MachopCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["MagikarpCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_BIG_HIT" },
  ["MagmarLv24Card"] = { "ATK_ANIM_FIRE_PUNCH", "ATK_ANIM_BIG_FLAME" },
  ["MagmarLv31Card"] = { "ATK_ANIM_DARK_GAS", "ATK_ANIM_SMOG" },
  ["MagnemiteLv13Card"] = { "ATK_ANIM_THUNDER_WAVE", "ATK_ANIM_SELFDESTRUCT" },
  ["MagnemiteLv15Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_MAGNETIC_STORM" },
  ["MagnetonLv28Card"] = { "ATK_ANIM_THUNDER_WAVE", "ATK_ANIM_BIG_SELFDESTRUCTION" },
  ["MagnetonLv35Card"] = { "ATK_ANIM_SONICBOOM", "ATK_ANIM_BIG_SELFDESTRUCTION" },
  ["MankeyCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_SLASH" },
  ["MarowakLv26Card"] = { "ATK_ANIM_BONEMERANG", "ATK_ANIM_GLOW_EFFECT" },
  ["MarowakLv32Card"] = { "ATK_ANIM_BONEMERANG", "ATK_ANIM_CRY" },
  ["MeowthLv14Card"] = { "ATK_ANIM_CAT_PUNCH", "ATK_ANIM_NONE" },
  ["MeowthLv15Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["MetapodCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_POWDER_EFFECT_CHANCE" },
  ["MewLv15Card"] = { "ATK_ANIM_HIT_EFFECT", "ATK_ANIM_NONE" },
  ["MewLv23Card"] = { "ATK_ANIM_PSYCHIC_HIT", "ATK_ANIM_NONE" },
  ["MewLv8Card"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_PSYCHIC_HIT" },
  ["MewtwoAltLV60Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_PSYCHIC_HIT" },
  ["MewtwoLv53Card"] = { "ATK_ANIM_PSYCHIC_HIT", "ATK_ANIM_BARRIER" },
  ["MewtwoLv60Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_PSYCHIC_HIT" },
  ["MoltresLv35Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_NONE" },
  ["MoltresLv37Card"] = { "ATK_ANIM_FIREGIVER", "ATK_ANIM_NONE" },
  ["MrMimeCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_PSYCHIC_HIT" },
  ["MukCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_GOO" },
  ["NidokingCard"] = { "ATK_ANIM_MULTIPLE_SLASH", "ATK_ANIM_TOXIC" },
  ["NidoqueenCard"] = { "ATK_ANIM_BOYFRIENDS", "ATK_ANIM_HIT" },
  ["NidoranFCard"] = { "ATK_ANIM_MULTIPLE_SLASH", "ATK_ANIM_GLOW_EFFECT" },
  ["NidoranMCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_NONE" },
  ["NidorinaCard"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_HIT" },
  ["NidorinoCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_DRILL" },
  ["NinetalesLv32Card"] = { "ATK_ANIM_LURE", "ATK_ANIM_FIRE_SPIN" },
  ["NinetalesLv35Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_FIRE_SPIN" },
  ["OddishCard"] = { "ATK_ANIM_POWDER_EFFECT_CHANCE", "ATK_ANIM_GLOW_EFFECT" },
  ["OmanyteCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_WATER_GUN" },
  ["OmastarCard"] = { "ATK_ANIM_WATER_GUN", "ATK_ANIM_NEEDLES" },
  ["OnixCard"] = { "ATK_ANIM_ROCK_THROW", "ATK_ANIM_PROTECT" },
  ["ParasCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_SPORE" },
  ["ParasectCard"] = { "ATK_ANIM_SPORE", "ATK_ANIM_SLASH" },
  ["PersianCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_HIT" },
  ["PidgeotLv38Card"] = { "ATK_ANIM_WHIRLWIND_ZIGZAG", "ATK_ANIM_GLOW_EFFECT" },
  ["PidgeotLv40Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_WHIRLWIND" },
  ["PidgeottoCard"] = { "ATK_ANIM_WHIRLWIND", "ATK_ANIM_MIRROR_MOVE" },
  ["PidgeyCard"] = { "ATK_ANIM_WHIRLWIND", "ATK_ANIM_NONE" },
  ["PikachuAltLv16Card"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_THUNDERSHOCK" },
  ["PikachuLv12Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_THUNDERSHOCK" },
  ["PikachuLv14Card"] = { "ATK_ANIM_THUNDER_WHOLE_SCREEN", "ATK_ANIM_NONE" },
  ["PikachuLv16Card"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_THUNDERSHOCK" },
  ["PinsirCard"] = { "ATK_ANIM_HIT_EFFECT", "ATK_ANIM_SONICBOOM" },
  ["PoliwagCard"] = { "ATK_ANIM_WATER_GUN", "ATK_ANIM_NONE" },
  ["PoliwhirlCard"] = { "ATK_ANIM_AMNESIA", "ATK_ANIM_HIT" },
  ["PoliwrathCard"] = { "ATK_ANIM_WATER_GUN", "ATK_ANIM_WHIRLPOOL" },
  ["PonytaCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_BIG_FLAME" },
  ["PorygonCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_GLOW_EFFECT" },
  ["PrimeapeCard"] = { "ATK_ANIM_MULTIPLE_SLASH", "ATK_ANIM_RAMPAGE" },
  ["PsyduckCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_MULTIPLE_SLASH" },
  ["RaichuLv40Card"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_THUNDER" },
  ["RaichuLv45Card"] = { "ATK_ANIM_THUNDER_WHOLE_SCREEN", "ATK_ANIM_NONE" },
  ["RapidashCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_QUICK_ATTACK" },
  ["RaticateCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_HIT" },
  ["RattataCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["RhydonCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_HIT_RECOIL" },
  ["RhyhornCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_HIT" },
  ["SandshrewCard"] = { "ATK_ANIM_DARK_GAS", "ATK_ANIM_NONE" },
  ["SandslashCard"] = { "ATK_ANIM_SLASH", "ATK_ANIM_MULTIPLE_SLASH" },
  ["ScytherCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_SLASH" },
  ["SeadraCard"] = { "ATK_ANIM_WATER_GUN", "ATK_ANIM_QUICK_ATTACK" },
  ["SeakingCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_WATER_JETS" },
  ["SeelCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["ShellderCard"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_NONE" },
  ["SlowbroCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_PSYCHIC_HIT" },
  ["SlowpokeLv18Card"] = { "ATK_ANIM_NONE", "ATK_ANIM_GLOW_EFFECT" },
  ["SlowpokeLv9Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_AMNESIA" },
  ["SnorlaxCard"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_BIG_HIT" },
  ["SpearowCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_MIRROR_MOVE" },
  ["SquirtleCard"] = { "ATK_ANIM_BUBBLES", "ATK_ANIM_NONE" },
  ["StarmieCard"] = { "ATK_ANIM_RECOVER", "ATK_ANIM_BEAM" },
  ["StaryuCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["SurfingPikachuAltLv13Card"] = { "ATK_ANIM_WATER_JETS", "ATK_ANIM_NONE" },
  ["SurfingPikachuLv13Card"] = { "ATK_ANIM_WATER_JETS", "ATK_ANIM_NONE" },
  ["TangelaLv12Card"] = { "ATK_ANIM_POWDER_EFFECT_CHANCE", "ATK_ANIM_POISON_WHIP" },
  ["TangelaLv8Card"] = { "ATK_ANIM_HIT", "ATK_ANIM_POWDER_HIT_POISON" },
  ["TaurosCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_RAMPAGE" },
  ["TentacoolCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_GOO" },
  ["TentacruelCard"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_MULTIPLE_SLASH" },
  ["VaporeonLv29Card"] = { "ATK_ANIM_GLOW_EFFECT", "ATK_ANIM_HIT" },
  ["VaporeonLv42Card"] = { "ATK_ANIM_QUICK_ATTACK", "ATK_ANIM_WATER_GUN" },
  ["VenomothCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_POWDER_EFFECT_CHANCE" },
  ["VenonatCard"] = { "ATK_ANIM_POWDER_EFFECT_CHANCE", "ATK_ANIM_DRAIN" },
  ["VenusaurLv64Card"] = { "ATK_ANIM_SOLAR_POWER", "ATK_ANIM_DRAIN" },
  ["VenusaurLv67Card"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_BEAM" },
  ["VictreebelCard"] = { "ATK_ANIM_LURE", "ATK_ANIM_GOO" },
  ["VileplumeCard"] = { "ATK_ANIM_PKMN_POWER_1", "ATK_ANIM_PETAL_DANCE" },
  ["VoltorbCard"] = { "ATK_ANIM_HIT", "ATK_ANIM_NONE" },
  ["VulpixCard"] = { "ATK_ANIM_CONFUSE_RAY", "ATK_ANIM_NONE" },
  ["WartortleCard"] = { "ATK_ANIM_NONE", "ATK_ANIM_HIT" },
  ["WeedleCard"] = { "ATK_ANIM_NEEDLES", "ATK_ANIM_NONE" },
  ["WeepinbellCard"] = { "ATK_ANIM_POWDER_EFFECT_CHANCE", "ATK_ANIM_WHIP" },
  ["WeezingCard"] = { "ATK_ANIM_SMOG", "ATK_ANIM_SELFDESTRUCT" },
  ["WigglytuffCard"] = { "ATK_ANIM_LULLABY", "ATK_ANIM_HIT" },
  ["ZapdosLv40Card"] = { "ATK_ANIM_THUNDERSTORM", "ATK_ANIM_NONE" },
  ["ZapdosLv64Card"] = { "ATK_ANIM_THUNDER", "ATK_ANIM_THUNDERBOLT" },
  ["ZapdosLv68Card"] = { "ATK_ANIM_PEAL_OF_THUNDER", "ATK_ANIM_BIG_THUNDER" },
  ["ZubatCard"] = { "ATK_ANIM_SUPERSONIC", "ATK_ANIM_DRAIN" },
}

Animations.sequences = {
  ["ATK_ANIM_AGILITY_PROTECT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_SPEED" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" }, { target="player", id="DUEL_ANIM_PROTECT" } },
  ["ATK_ANIM_AMNESIA"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_QUESTION_MARK" } },
  ["ATK_ANIM_BARRIER"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_BARRIER" } },
  ["ATK_ANIM_BEAM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BEAM" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BENCH_HIT"] = {  },
  ["ATK_ANIM_BIG_FLAME"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BIG_FLAME" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BIG_HIT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BIG_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE2" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BIG_SELFDESTRUCTION"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_BIG_SELFDESTRUCT_1" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="player", id="DUEL_ANIM_BIG_SELFDESTRUCT_2" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BIG_THUNDER"] = { { target="player", id="DUEL_ANIM_GLOW" } },
  ["ATK_ANIM_BLIZZARD"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_BLIZZARD" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BONEMERANG"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BONEMERANG" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BOYFRIENDS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BOYFRIENDS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_BUBBLES"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BUBBLES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_CAT_PUNCH"] = { { target="player", id="DUEL_ANIM_GLOW" } },
  ["ATK_ANIM_CAT_PUNCH_PLAY_AREA"] = { { target="normal", id="DUEL_ANIM_SHAKE1" } },
  ["ATK_ANIM_CHAIN_LIGHTNING"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="normal", id="DUEL_ANIM_BIG_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_CONFUSE_RAY"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="opponent", id="DUEL_ANIM_CONFUSE_RAY" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_CONFUSION"] = { { target="opponent", id="DUEL_ANIM_CONFUSION" } },
  ["ATK_ANIM_CONFUSION_HIT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_CONFUSION" }, { target="player", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE3" }, { target="player", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_CRY"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_CRY" }, { target="normal", id="DUEL_ANIM_SHAKE1" } },
  ["ATK_ANIM_DARK_GAS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_DARK_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" }, { target="opponent", id="DUEL_ANIM_QUESTION_MARK" } },
  ["ATK_ANIM_DARK_MIND"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_LEER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_DEVOLUTION_BEAM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_DIVE_BOMB"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_DIVE_BOMB" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_DRAGON_RAGE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_WATER_GUN" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_DRAIN"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_DRAIN" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_DRILL"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_DRILL" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_ENERGY_CONVERSION"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_EXPAND"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_EXPAND" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_FIREGIVER"] = { { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_FIREGIVER_OPP"] = { { target="normal", id="DUEL_ANIM_FIREGIVER_OPP" } },
  ["ATK_ANIM_FIREGIVER_PLAYER"] = { { target="normal", id="DUEL_ANIM_FIREGIVER_PLAYER" } },
  ["ATK_ANIM_FIRE_PUNCH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_FIRE_PUNCH" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_FIRE_SPIN"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FIRE_SPIN" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_FOUL_GAS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_FOUL_ODOR"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_FRIENDSHIP_SONG"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_SING" } },
  ["ATK_ANIM_FULL_HEAL"] = { { target="player", id="DUEL_ANIM_HEAL" }, { target="normal", id="DUEL_ANIM_UPDATE_HUD" } },
  ["ATK_ANIM_GALE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHIRLWIND" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" }, { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_GLOW_EFFECT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_GOO"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_GOO" }, { target="normal", id="DUEL_ANIM_DISTORT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_GUST_OF_WIND"] = { { target="opponent", id="DUEL_ANIM_WHIRLWIND" } },
  ["ATK_ANIM_HEAL"] = { { target="player", id="DUEL_ANIM_HEAL" }, { target="player", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HEALING_WIND"] = {  },
  ["ATK_ANIM_HEALING_WIND_PLAY_AREA"] = {  },
  ["ATK_ANIM_HEAL_BOTH_SIDES"] = { { target="player", id="DUEL_ANIM_HEAL" }, { target="opponent", id="DUEL_ANIM_HEAL" } },
  ["ATK_ANIM_HIT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HIT_EFFECT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HIT_RECOIL"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HYDRO_PUMP"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HYDRO_PUMP" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HYPER_BEAM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HYPER_BEAM" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_HYPNOSIS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_PSYCHIC" } },
  ["ATK_ANIM_LEER"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_LEER" }, { target="opponent", id="DUEL_ANIM_QUESTION_MARK" } },
  ["ATK_ANIM_LULLABY"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SING" } },
  ["ATK_ANIM_LURE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_LURE" }, { target="normal", id="DUEL_ANIM_DISTORT" } },
  ["ATK_ANIM_MAGNETIC_STORM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_THUNDER_WAVE" } },
  ["ATK_ANIM_MIRROR_MOVE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="opponent", id="DUEL_ANIM_GLOW" } },
  ["ATK_ANIM_MULTIPLE_SLASH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_FURY_SWIPES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_NEEDLES"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_NEEDLES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_NIGHTMARE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_PSYCHIC" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_NONE"] = {  },
  ["ATK_ANIM_OWN_CONFUSION"] = { { target="player", id="DUEL_ANIM_CONFUSION" } },
  ["ATK_ANIM_PARALYSIS"] = { { target="opponent", id="DUEL_ANIM_PARALYSIS" } },
  ["ATK_ANIM_PEAL_OF_THUNDER"] = { { target="normal", id="DUEL_ANIM_SHAKE1" } },
  ["ATK_ANIM_PETAL_DANCE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_PETAL_DANCE" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_PKMN_POWER_1"] = { { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_POISON"] = { { target="opponent", id="DUEL_ANIM_POISON" } },
  ["ATK_ANIM_POISON_FANG"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_POISON_POWDER"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" } },
  ["ATK_ANIM_POISON_WHIP"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHIP" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_POT_SMASH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POT_SMASH" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_POWDER_EFFECT_CHANCE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_POWDER_HIT_POISON"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_PROTECT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_PROTECT" } },
  ["ATK_ANIM_PSYCHIC_HIT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_PSYCHIC" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_PUNCH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_PUNCH" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_QUICKFREEZE"] = { { target="normal", id="DUEL_ANIM_QUICKFREEZE" } },
  ["ATK_ANIM_QUICK_ATTACK"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_SPEED" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_RAMPAGE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_FURY_SWIPES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_RECOIL_HIT"] = { { target="player", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE3" }, { target="player", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_RECOVER"] = { { target="player", id="DUEL_ANIM_GLOW" } },
  ["ATK_ANIM_ROCK_THROW"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_ROCK_THROW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SCRUNCH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_EXPAND" } },
  ["ATK_ANIM_SEISMIC_TOSS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SEISMIC_TOSS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SELFDESTRUCT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_SELFDESTRUCT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SING"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SING" } },
  ["ATK_ANIM_SLASH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SLASH" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SLEEP"] = { { target="opponent", id="DUEL_ANIM_SLEEP" } },
  ["ATK_ANIM_SLEEPING_GAS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" } },
  ["ATK_ANIM_SMALL_FLAME"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SMALL_FLAME" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SMOG"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SOLAR_POWER"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" } },
  ["ATK_ANIM_SONICBOOM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SONICBOOM" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SPIT_POISON"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_GOO" }, { target="normal", id="DUEL_ANIM_DISTORT" } },
  ["ATK_ANIM_SPIT_POISON_SUCCESS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_GOO" }, { target="normal", id="DUEL_ANIM_DISTORT" } },
  ["ATK_ANIM_SPORE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" } },
  ["ATK_ANIM_STONE_BARRAGE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_STONE_BARRAGE" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_STRETCH_KICK"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_STRETCH_KICK" } },
  ["ATK_ANIM_STRING_SHOT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_STRING_SHOT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_SUPERSONIC"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SUPERSONIC" } },
  ["ATK_ANIM_THUNDER"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_THUNDER_SHOCK" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDERBOLT"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_BORDER_SPARK" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDERPUNCH"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_THUNDERPUNCH" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDERSHOCK"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_THUNDER_SHOCK" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDERSTORM"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="normal", id="DUEL_ANIM_BIG_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDER_PLAY_AREA"] = { { target="normal", id="DUEL_ANIM_SHAKE1" } },
  ["ATK_ANIM_THUNDER_WAVE"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_THUNDER_WAVE" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_THUNDER_WHOLE_SCREEN"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="normal", id="DUEL_ANIM_BIG_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_TOXIC"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_DISTORT" }, { target="opponent", id="DUEL_ANIM_TOXIC" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_03"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_09"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_THUNDER_SHOCK" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_0B"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="normal", id="DUEL_ANIM_BIG_LIGHTNING" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_17"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_BLIZZARD" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_1B"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_PSYCHIC" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_1F"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BEAM" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_2A"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_FURY_SWIPES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_31"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_NEEDLES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_33"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_34"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHITE_GAS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_3A"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_3B"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_3C"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_POWDER" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_3E"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_GOO" }, { target="normal", id="DUEL_ANIM_DISTORT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_40"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_GOO" }, { target="normal", id="DUEL_ANIM_DISTORT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_42"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_BUBBLES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_44"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_STRING_SHOT" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_49"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_FLASH" }, { target="opponent", id="DUEL_ANIM_CONFUSE_RAY" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_4D"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_SUPERSONIC" } },
  ["ATK_ANIM_UNUSED_67"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_68"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_69"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_NEEDLES" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_70"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="player", id="DUEL_ANIM_THUNDER_WAVE" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_76"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_WATER_JETS" } },
  ["ATK_ANIM_UNUSED_77"] = {  },
  ["ATK_ANIM_UNUSED_81"] = { { target="opponent", id="DUEL_ANIM_QUESTION_MARK" } },
  ["ATK_ANIM_UNUSED_89"] = { { target="player", id="DUEL_ANIM_POISON" }, { target="player", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_UNUSED_8B"] = { { target="player", id="DUEL_ANIM_SLEEP" }, { target="normal", id="DUEL_ANIM_UPDATE_HUD" } },
  ["ATK_ANIM_UNUSED_8F"] = {  },
  ["ATK_ANIM_UNUSED_90"] = {  },
  ["ATK_ANIM_WATER_GUN"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WATER_GUN" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_WATER_JETS"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_WATER_JETS" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_WHIP"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHIP" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_WHIRLPOOL"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_WHIRLPOOL" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_WHIRLWIND"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="opponent", id="DUEL_ANIM_WHIRLWIND" }, { target="opponent", id="DUEL_ANIM_HIT" }, { target="normal", id="DUEL_ANIM_SHAKE1" }, { target="opponent", id="DUEL_ANIM_SHOW_DAMAGE" } },
  ["ATK_ANIM_WHIRLWIND_ZIGZAG"] = { { target="player", id="DUEL_ANIM_GLOW" }, { target="normal", id="DUEL_ANIM_BENCH_WHIRLWIND" } },
}

local asset_overrides = {
  THUNDER_SHOCK="lightning", LIGHTNING="lightning", BORDER_SPARK="spark",
  BIG_LIGHTNING="big_lightning", SMALL_FLAME="flame", BIG_FLAME="flame",
  WATER_JETS="water_gun", WATER_GUN="water_gun", BUBBLES="bubble",
  PSYCHIC="psychic", BIG_HIT="hit", SHAKE1="hit", SHAKE2="hit",
  SHOW_DAMAGE="damage", STONE_BARRAGE="rock_throw", THUNDERPUNCH="punch",
  FIRE_PUNCH="punch", MULTIPLE_SLASH="slash", WHITE_GAS="gas",
  POWDER_HIT="powder", GOO_HIT="goo", CONFUSE_RAY="psychic",
  SING="note", SUPERSONIC="sound", AGILITY="speed", DARK_GAS="gas",
  GLOW_EFFECT="glow", QUICKFREEZE="snow", PEAL_OF_THUNDER="big_lightning",
  HEALING_WIND="heal", SOLAR_POWER="glow", POISON_WHIP="whip",
  THUNDER_WAVE="lightning", HYPNOSIS="sleep", ENERGY_CONVERSION="glow",
  CONFUSION_HIT="psychic", RECOIL_HIT="hit", POISON_DAMAGE="poison",
  SLEEPING_GAS="gas", CAT_PUNCH_PLAY_AREA="cat_paw", FIREGIVER="flame",
  HEALING_WIND_PLAY_AREA="heal", FULL_HEAL="heal", HEAL_BOTH_SIDES="heal",
}

function Animations.forAttack(card_label, attack_index)
  local slots = Animations.card_attacks[card_label]
  local id = slots and slots[attack_index or 1] or "ATK_ANIM_HIT"
  if id == "ATK_ANIM_NONE" then id = "ATK_ANIM_GLOW_EFFECT" end
  return id, Animations.sequences[id] or Animations.sequences.ATK_ANIM_HIT or {}
end

function Animations.assetFor(duel_id)
  local short = tostring(duel_id or ""):gsub("^DUEL_ANIM_", "")
  local name = asset_overrides[short] or short:lower()
  return name .. ".png"
end

return Animations
